from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.platform.identity.model import (
    AccessStatus,
    AuthSession,
    CompanyAccess,
    Permission,
    RefreshTokenRecord,
    Role,
    RoleAssignment,
    TenantMembership,
    UserAccount,
    UserStatus,
)


class IdentityRepository(Protocol):
    def add_user(self, user: UserAccount) -> None: ...
    def get_user_by_id(self, user_id: UUID) -> UserAccount | None: ...
    def get_user_by_normalized_login(self, login_normalized: str) -> UserAccount | None: ...
    def set_user_status(self, user_id: UUID, status: UserStatus, updated_at: datetime) -> None: ...
    def set_password_hash(self, user_id: UUID, password_hash: str, updated_at: datetime) -> None: ...
    def get_password_hash(self, user_id: UUID) -> str | None: ...
    def add_session(self, session: AuthSession) -> None: ...
    def get_session(self, session_id: UUID) -> AuthSession | None: ...
    def touch_session(self, session_id: UUID, at: datetime) -> None: ...
    def revoke_session(self, session_id: UUID, at: datetime) -> None: ...
    def revoke_all_sessions(self, user_id: UUID, at: datetime) -> None: ...
    def add_refresh_token(self, token: RefreshTokenRecord) -> None: ...
    def get_refresh_by_hash(self, token_hash: str) -> RefreshTokenRecord | None: ...
    def consume_refresh(self, token_id: UUID, at: datetime) -> bool: ...
    def revoke_refresh_family(self, family_id: UUID, at: datetime) -> None: ...
    def revoke_refresh_for_session(self, session_id: UUID, at: datetime) -> None: ...
    def revoke_refresh_for_user(self, user_id: UUID, at: datetime) -> None: ...
    def add_membership(self, membership: TenantMembership) -> None: ...
    def get_membership(self, user_id: UUID, tenant_id: UUID) -> TenantMembership | None: ...
    def list_memberships(self, user_id: UUID) -> Sequence[TenantMembership]: ...
    def set_membership_status(
        self, membership_id: UUID, status: AccessStatus, updated_at: datetime
    ) -> None: ...
    def add_company_access(self, access: CompanyAccess) -> None: ...
    def get_company_access(self, membership_id: UUID, company_id: UUID) -> CompanyAccess | None: ...
    def list_company_access(self, membership_id: UUID) -> Sequence[CompanyAccess]: ...
    def set_company_access_status(
        self,
        membership_id: UUID,
        company_id: UUID,
        status: AccessStatus,
        updated_at: datetime,
    ) -> None: ...
    def add_permission(self, permission: Permission) -> None: ...
    def get_permission_by_code(self, code: str) -> Permission | None: ...
    def add_role(self, role: Role) -> None: ...
    def get_role_by_code(self, code: str) -> Role | None: ...
    def grant_permission_to_role(self, role_id: UUID, permission_id: UUID) -> None: ...
    def add_role_assignment(self, assignment: RoleAssignment) -> None: ...
    def delete_role_assignment(self, assignment_id: UUID) -> None: ...
    def list_role_assignments(self, user_id: UUID) -> Sequence[RoleAssignment]: ...
    def get_roles(self, role_ids: Sequence[UUID]) -> Sequence[Role]: ...
    def get_permission_codes_by_roles(
        self, role_ids: Sequence[UUID]
    ) -> dict[UUID, frozenset[str]]: ...
